Mavlutov91/cha 26 создать механику игры на canvas api
cupOfTea321/chapecker pull request #12
Opened 2023-10-27 19:26 UTC by Vampiracus

### Пишем игровой движок

#### Сейчас реализовано:
- Игровое поле
- Возможность выбрать активную фишку

![image](https://github.com/cupOfTea321/chapecker/assets/53150722/9a54f9eb-6692-4c36-8677-780aafdf6f78)

2023-11-02 10:11 UTC, johnyslima approved these changes

2023-11-02 10:11 UTC, johnyslima commented on packages/client/src/pages/Game/Engine/Checker.ts
> +    console.log(this, other)
вообще по хорошему консоль-логи нужно убирать когда мы мерждим в главную ветку.  Сейчас можно оставить, но это так совет на будущее.

2023-11-02 10:11 UTC, johnyslima commented on packages/client/src/pages/Game/Engine/Checker.ts
> +function dist(x1: number, y1: number, x2: number, y2: number): number {
вот эти две функции (dist и vlength), я думаю можно смело поместить в класс Checker  как приватные. Но это только если мы используем их в рамках класса Checker. В противном случае такие функции лучше выносить в какие-нибудь utils.ts

2023-11-03 17:49 UTC, mcf11y commented on packages/client/src/pages/Forum/ForumPage.tsx
> +            key={tab.split(' ').join('')}
раз уж потрогал)
не надо такие ключи делать с циклами - у тебя там и split и join 0(n) - и это только для выбора ключа

2023-11-03 17:49 UTC, mcf11y commented on packages/client/src/pages/Game/Engine/Checkers.ts
> +  public async init(): Promise<boolean> {
а почему возвращаемый тип Promise, или это на будущее?

2023-11-03 17:49 UTC, mcf11y commented on packages/client/src/pages/Game/GamePage.tsx
> +  }, [canvasRef, gameRef])
в deps effect'ов (useMemo/useCallback) нету смысла указывать ссылки (ref) - оно "работает" (реагирует) только с примитивами

по итогу эффект сработает 1 раз после рендера (локально 2 в strict mode react v18)

2023-11-03 17:49 UTC, mcf11y commented on yarn.lock
> +"client@file:C:\\Users\\Максим\\Downloads\\Practicum\\chapecker\\packages\\client":
почему это изменилось?)

2023-11-03 18:26 UTC, Olegas commented on packages/client/src/pages/Game/GamePage.tsx
> +  }, [canvasRef, gameRef])
Еще замечание тут - экземпляр gameEngine сохранили в глобальную переменную. И нигде потом не зачистили. Так будут утечки. Лучше сохранить его в ref.

2023-11-03 18:27 UTC, Olegas requested changes
Все круто, особенно скрин тетрадки )
Есть одна проблема - глобальная переменная с GameEngine. Надо исправить

2023-11-04 08:07 UTC, Vampiracus commented on packages/client/src/pages/Game/Engine/Checkers.ts
> +  public async init(): Promise<boolean> {
Наоборот, по историческим причинам. Там раньше подгружались спрайты и звуки. Поскольку мы отказались и от того, и от другого, в промисах действительно больше нет необходимости

2023-11-04 08:33 UTC, Vampiracus commented on packages/client/src/pages/Game/GamePage.tsx
> +  }, [canvasRef, gameRef])
Добрый день! Я убрал экземпляр gameEngine в ref канваса, но все равно немного не понял про утечки. 
Согласен, что в такой реализации при переходе на другую станицу gameEngine не удаляется, а продолжает существовать. Но если вернуться на страницу игры, ведь новый экземпляр не будет создан? В прошлом модуле говорилось, что код в js-модулях выполняется единожды. Разве это не значит, что единовременно в приложении будет не больше одного экземпляра gameEngine? Откуда тогда утечки?

2023-11-04 10:27 UTC, Olegas commented on packages/client/src/pages/Game/GamePage.tsx
> +  }, [canvasRef, gameRef])
@Vampiracus не надо убирать в ref канваса, его надо убирать в свой собственный ref. Ref можно использовать не только для DOM-элементов, но и для чего угодно, что не должно триггерить перерисовку при изменении содержимого. Сделайте отдельный ref и сложите в него экземпляр GameEngine. 
Утечка - потому что вы со страницы игры ушли, а данные от компонента - остались в памяти. Не думаю что это ожидаемое поведение.

2023-11-04 13:00 UTC, Vampiracus commented on packages/client/src/pages/Game/GamePage.tsx
> +  }, [canvasRef, gameRef])
@Olegas поправил

2023-11-04 19:12 UTC, Olegas approved these changes
Работа принята

2023-11-05 13:00 UTC, merged