Vityakunin/cha 22
cupOfTea321/chapecker pull request #13
Opened 2023-10-28 23:18 UTC by WilhelmYakunin

### Сверстать страницу пользователя

### 1. Сверстать страницу профиля. 

2. [Подключить API смены пароля](https://ya-praktikum.tech/api/v2/swagger/#/Users/put_user_password). 

3. Сверстать компонент изменения аватара. 

4. [Подключить API для смены аватара пользователя](https://ya-praktikum.tech/api/v2/swagger/#/Users/put_user_profile_avatar).

Ожидание:

Страница с информацией о пользователе, возможностью загрузить и сменить аватар, изменить пароль (используйте [API](https://ya-praktikum.tech/api/v2/swagger/#/)).

### TBD [(если есть)](https://linear.app/chapecker/issue/CHA-22/sverstat-stranicu-polzovatelya)

2023-10-29 19:34 UTC, Vampiracus requested changes
Привет!

Ты проделал впечатляюще большую работу и создал очень крутую по функциональности и оформлению страницу! Меня особо впечатляет оформление с разнообразными картинками и, конечно, усы

Все же, я уверен, что нужно сделать некоторые изменения. Я постарался подробно расписать почти по моментам, что стоит сделать, ниже, рядом с кодом. Здесь дополню сказанное ниже:
- Организацию содержимого папки `pages/Profile` можно улучшить: все кастомные компоненты вместе с файлами, которые к ним относятся, и стилями стоит вынести в папку `pages/Profile/components`. Вне её оставить только то, что относится непосредственно к файлу `ProfilePage.tsx`
- Картинки для форм смены логина и пароля продублированы в `src/pages/Profile/pictures` и в `src/assets`. Стоит оставить картинки в одном экземпляре

2023-10-29 19:34 UTC, makxca commented on packages/client/src/pages/Profile/pictures/changePassword.svg
_Комментарий_

Этот файл уже есть в `src/assets`

2023-10-29 19:34 UTC, makxca commented on packages/client/src/assets/changePassword.svg
_Комментарий_

Этот файл продублирован в `src/pages/Profile/pictures`

2023-10-29 19:34 UTC, makxca commented on packages/client/src/assets/userData.svg
_Комментарий_

Этот файл продублирован в src/pages/Profile/pictures

2023-10-29 19:34 UTC, makxca commented on packages/client/src/pages/Profile/pictures/userData.svg
_Комментарий_

Этот файл уже есть в src/assets

2023-10-29 19:34 UTC, makxca commented on packages/client/src/API/endpoints.ts
> +export const changePasswordEndpoint = baseEndpoint.concat('/user/password')
_Комментарий_

Отлично, что все урлы вынесены в отдельный файл

2023-10-29 19:34 UTC, makxca commented on packages/client/src/pages/Profile/ProfilePage.tsx
**_Нужно внести изменения_**

У компонента 200 строк! Его можно уменьшить, разбив на отдельные компоненты и расчленив логику. Это намного повысит читаемость кода. Мы ещё будем возвращаться к этому коду, поэтому, обеспечивая читаемость кода, мы в первую очередь заботимся о себе.

Стоит вынести отдельными компонентами формы смены пароля и смены данных пользователя. 

Оставил ещё предложения по более мелким кускам логики ниже

2023-10-29 19:34 UTC, makxca commented on packages/client/src/pages/Profile/ProfilePage.tsx
> +        </div>
_Комментарий_

Шапку сайта можно вынести отдельным компонентом

2023-10-29 19:34 UTC, makxca commented on packages/client/src/pages/Profile/ProfilePage.tsx
> +              </div>
_Комментарий_

Кнопки управления можно вынести в отдельный компонент

2023-10-29 19:34 UTC, makxca commented on packages/client/src/pages/Profile/ProfilePage.tsx
> +      }
**_Нужно внести изменения_**

Не стоит выкидывать ошибку, потому что она ломает приложение. Если пользователь ввел различающиеся пароли, лучше просто как-то дать ему понять, что он ввел неправильные данные, например, перекрасить инпуты в красный цвет

2023-10-29 19:34 UTC, makxca commented on packages/client/src/API/endpoints.ts
> +const baseEndpoint = 'ya-praktikum.tech/api/v2'
**_Нужно внести изменения_**

Сейчас все запросы отправляются по адресу:
` http://localhost:3000/ya-praktikum.tech/api/v2/`
Чтобы это исправить, пожалуйста, присвой baseEndpoint значение:
`https://ya-praktikum.tech/api/v2`

2023-10-29 19:34 UTC, Vampiracus commented on packages/client/src/pages/Profile/mustache/Mustache.tsx
> +
Это великолепно! Не знал, ты очень круто нарисовал анимированные усы, используя только html и css!

2023-10-29 19:34 UTC, Vampiracus commented on packages/client/src/pages/Profile/styles.scss
Пожалуйста, разбей этот файл со стилями всей страницы на файлы в соответствии с разбиением страницы на компонент

2023-10-29 19:34 UTC, Vampiracus commented on packages/client/src/pages/Profile/ProfilePage.tsx
> +        </div>
Когда я переключаюсь на "Смену пароля", слайдер переезжает вправо, но не уменьшается в длине. Поэтому страница заметно удлиняется вправо и появляется некрасивый выступ справа и два слайдера

![image](https://github.com/cupOfTea321/chapecker/assets/53150722/975e84d6-0212-440f-bcf8-f2be2629d974)

2023-10-29 19:34 UTC, Vampiracus commented on packages/client/src/pages/Profile/ProfilePage.tsx
> +                />
Мне кажется, лучше выбрать какое-то другое название для кнопки, чтобы дать пользователю понять "Кликни меня, и ты сможешь менять данные в форме". Пока я не кликнул кнопку, я думал, что поля формы менять нельзя. Возможно что-то типа "поменять данные профиля" или "хочу изменить данные" здесь подойдет лучше

2023-10-29 19:34 UTC, Vampiracus commented on packages/client/src/pages/Profile/styles.scss
> +
Слиплись кнопки. 

![image](https://github.com/cupOfTea321/chapecker/assets/53150722/0ac8577e-3662-4bbb-b69c-7d7ab962de58)

Чтобы между ними был минимальный зазор, можно здесь добавить
```
& > input {
 margin: 3px;
}
```
![image](https://github.com/cupOfTea321/chapecker/assets/53150722/6c7c1f20-52b7-4d64-9d12-5afa96a9a390)

2023-10-30 16:50 UTC, WilhelmYakunin commented on packages/client/src/pages/Profile/pictures/userData.svg
Картинки сознательно оставлены в папке страницы и в /assets. Пока не известно как состоится деплой и откуда из будет "брать" приложение. Поэтому они есть и там и там. Так не должны потеряться.

2023-10-30 16:50 UTC, WilhelmYakunin commented on packages/client/src/assets/userData.svg
Картинки сознательно оставлены в папке страницы и в /assets. Пока не известно как состоится деплой и откуда из будет "брать" приложение. Поэтому они есть и там и там. Так не должны потеряться.

2023-10-30 16:50 UTC, WilhelmYakunin commented on packages/client/src/assets/changePassword.svg
Картинки сознательно оставлены в папке страницы и в /assets. Пока не известно как состоится деплой и откуда из будет "брать" приложение. Поэтому они есть и там и там. Так не должны потеряться.

2023-10-30 16:50 UTC, WilhelmYakunin commented on packages/client/src/pages/Profile/pictures/changePassword.svg
Картинки сознательно оставлены в папке страницы и в /assets. Пока не известно как состоится деплой и откуда из будет "брать" приложение. Поэтому они есть и там и там. Так не должны потеряться.

2023-10-30 16:52 UTC, WilhelmYakunin commented on packages/client/src/API/endpoints.ts
> +export const changePasswordEndpoint = baseEndpoint.concat('/user/password')
Endpoint - да. Так удобнее и понятнее

2023-10-30 16:54 UTC, WilhelmYakunin commented on packages/client/src/pages/Profile/mustache/Mustache.tsx
> +
Это же Чапайки.. Как иначе-то )
Кстсти у Ава пользователя тоже анимированные усы на подобие тех, когда нет авы.

2023-10-30 17:39 UTC, WilhelmYakunin commented on packages/client/src/pages/Profile/ProfilePage.tsx
> +        </div>
Был баг. И нет бага. Спасибо)

2023-10-30 17:43 UTC, WilhelmYakunin commented on packages/client/src/pages/Profile/styles.scss
> +
gap: 5px поставил в родителе. 
Само кнопки по идее не должны друг друга "толкать".

2023-10-30 17:46 UTC, WilhelmYakunin commented on packages/client/src/pages/Profile/ProfilePage.tsx
> +                />
So be it.

2023-10-30 17:54 UTC, WilhelmYakunin commented on packages/client/src/pages/Profile/styles.scss
Так было изначально, нет разве? Или я что-то упускаю?

2023-10-30 18:00 UTC, WilhelmYakunin commented
> Привет!
> 
> Ты проделал впечатляюще большую работу и создал очень крутую по функциональности и оформлению страницу! Меня особо впечатляет оформление с разнообразными картинками и, конечно, усы
> 
> Все же, я уверен, что нужно сделать некоторые изменения. Я постарался подробно расписать почти по моментам, что стоит сделать, ниже, рядом с кодом. Здесь дополню сказанное ниже:
> 
> * Организацию содержимого папки `pages/Profile` можно улучшить: все кастомные компоненты вместе с файлами, которые к ним относятся, и стилями стоит вынести в папку `pages/Profile/components`. Вне её оставить только то, что относится непосредственно к файлу `ProfilePage.tsx`
> * Картинки для форм смены логина и пароля продублированы в `src/pages/Profile/pictures` и в `src/assets`. Стоит оставить картинки в одном экземпляре
> 
> _P.S.: Чтобы как-то отделить ниже комментарии от того, что нуждается в изменении, оставил соответствующие приписки в начале каждого сообщения_

Привет!
Спасибо за высокую оценку. 
Не все замечания могу принять - смотри unresolved. Вынос картинок - думаю есть смысл обсуждать в дальнейшем, когда станет понятно куда из нужно выносить.

2023-11-01 04:48 UTC, Vampiracus commented on packages/client/src/API/endpoints.ts
> +const baseEndpoint = 'ya-praktikum.tech/api/v2'
@WilhelmYakunin баг актуален
![image](https://github.com/cupOfTea321/chapecker/assets/53150722/871b4b21-f8e9-4663-b1d5-f15df2de29b2)

2023-11-01 04:52 UTC, Vampiracus commented on packages/client/src/pages/Profile/ProfilePage.tsx
@WilhelmYakunin мне всё же кажется, стоит разбить компонент на более мелкие части. Тогда код станет прозрачнее: логика отдельных частей страницы будет находиться в отдельном месте, поэтому будет легче её если что править

2023-11-01 04:58 UTC, Vampiracus commented on packages/client/src/pages/Profile/ProfilePage.tsx
> +      }
Замечание актуально. Если пользователь нажал "отправить изменения", ошибочно введя различающиеся пароли в поля "новый пароль" и "подтверждение", то он может подумать, что изменения зафиксированы. Он же не будет открывать консоль и искать ошибки.
Где-то эта ошибка должна обрабатываться. Если нет желания этим заниматься, думаю, можно хотя бы и при помощи alert сказать, что введены плохие пароли.

2023-11-01 05:00 UTC, Vampiracus commented on packages/client/src/pages/Profile/styles.scss
@WilhelmYakunin
Сорри, неясно выразился. Имел в виду, что если будешь разбивать ProfilePage на компоненты, то не забудь разбить и этот файл

2023-11-01 05:00 UTC, Vampiracus commented on packages/client/src/pages/Profile/styles.scss
> +
Я не знал про свойство gap. Спасибо, возьму на вооружение!)

2023-11-01 05:08 UTC, Vampiracus commented
Привет!
Я добавил комментарии в некоторые места, где unresolved:
- По разбиению ProfilePage на более мелкие части
- По выбрасыванию ошибки при несовпадающих паролях
- По неправильному baseEndpoint

Я бы хотел, чтобы они тоже были учтены.

Поскольку работа проделана довольно большая, думаю, стоит привлечь ещё кого-то на ревью

2023-11-01 14:07 UTC, WilhelmYakunin commented on packages/client/src/pages/Profile/ProfilePage.tsx
> +      }
Думаю нужен отдельный компонент который появляется в случае ошибки. Хотя можно и нужно делать это через валидацию форм. У этой таски не эта цель.
Пока оставлю Alert(Пароли не совпадают).

2023-11-01 18:31 UTC, WilhelmYakunin commented on packages/client/src/pages/Profile/ProfilePage.tsx
Вынес формы в отдельные компоненты.
Я не заметил как страница стала в 200 строк... Сейчас 99. Все компоненты "глупые" - не знают о реализации функций actions.

2023-11-01 18:32 UTC, WilhelmYakunin commented on packages/client/src/pages/Profile/ProfilePage.tsx
> +        </div>
Кнопки тоже можно. И даже нужно...
Но пока не вынесли ;) У каждого свои кнопки получаются

2023-11-01 19:59 UTC, WilhelmYakunin commented on packages/client/src/API/endpoints.ts
> +const baseEndpoint = 'ya-praktikum.tech/api/v2'
Поправил.

2023-11-01 20:06 UTC, WilhelmYakunin commented
> Привет! Я добавил комментарии в некоторые места, где unresolved:
> 
> * По разбиению ProfilePage на более мелкие части
> * По выбрасыванию ошибки при несовпадающих паролях
> * По неправильному baseEndpoint
> 
> Я бы хотел, чтобы они тоже были учтены.
> 
> Поскольку работа проделана довольно большая, думаю, стоит привлечь ещё кого-то на ревью

Привет,

учтены.

2023-11-01 20:07 UTC, WilhelmYakunin commented on packages/client/src/pages/Profile/styles.scss
Ясно.

2023-11-01 20:08 UTC, WilhelmYakunin commented on packages/client/src/pages/Profile/ProfilePage.tsx
> +              </div>
Вынес форму в отдельный компонент.

2023-11-02 09:50 UTC, Vampiracus approved these changes
Ещё одна страница нашей игры готова!

2023-11-02 09:50 UTC, Vampiracus commented on packages/client/src/pages/Profile/ProfilePage.tsx
> +
Эти две функции не используют никакой логики из ProfilePage. Это значит, что их можно подвинуть ближе к месту, где они используются. Коллбек смены пароля к форме смены пароля, коллбек смены userdata - к форме смены userdata.

2023-11-03 13:58 UTC, WilhelmYakunin commented on packages/client/src/pages/Profile/ProfilePage.tsx
> +
По идее смена данных пользователя или пароля должна влиять на страницу профиля (спиннер, смена данных в satate). Обе формы здесь "глупые элементы", т.е. знают, что снаружи происходит. Пока эта связи не явная.

2023-11-04 17:59 UTC, cupOfTea321 commented
Действительно хороший дизайн с приятной анимацией. Отлично, что сделаны оптимизации с помощью Memo и Callback. Единственное по UI смущает, что при клике на аватар можно его поменять. Для этого уже есть кнопка снизу, так что стоит оставить загрузку только по клику на кнопку

Отлично, что Profile разбит на мелкие компоненты, так как на странице присутствует много логики. В дальнейшем нужно будет переписать запросы под формат RTK Query, добавив соответствующие эндпоинты

2023-11-04 19:11 UTC, WilhelmYakunin commented
> Действительно хороший дизайн с приятной анимацией. Отлично, что сделаны оптимизации с помощью Memo и Callback. Единственное по UI смущает, что при клике на аватар можно его поменять. Для этого уже есть кнопка снизу, так что стоит оставить загрузку только по клику на кнопку
> 
> Отлично, что Profile разбит на мелкие компоненты, так как на странице присутствует много логики. В дальнейшем нужно будет переписать запросы под формат RTK Query, добавив соответствующие эндпоинты

Поменял поведение - теперь по усам можно кликать спокойно)

2023-11-04 19:11 UTC, merged