Mavlutov91/cha 26 v1
cupOfTea321/chapecker pull request #15
Opened 2023-10-31 13:05 UTC by johnyslima

### Какую задачу решаем
https://linear.app/chapecker/issue/CHA-26/sozdat-mehaniku-igry-na-canvas-api
Написал первую версию игрового движка.
- событие старта
- луппинг
- отрисовка доски, фишек
- функционал для будущего добавления спрайтов, звуков

### Скриншоты/видяшка (если есть)

Задача была отчасти делегирована с @kudrin.ma2012. Так как у нас пропал один член когорты, я взял часть задач на него. Поэтому не смог закончить до конца. Для индивидуального зачета создал отдельную ветку со своими измененями.

2023-10-31 14:31 UTC, Vampiracus approved these changes

2023-10-31 15:05 UTC, Olegas requested changes
Добрый день.
В коде есть ошибки + очень много закомментированного кода. Не понятно как это все работает, что лишнее, что не доделано. Выглядит так, что задача не доделана до конца.
По коду движка не понятно как обрабатываются кнопки. Вижу что проставляется состояние какая кнопка была нажата, но не понял где это обрабатывается.
Надо привести код в порядок.

2023-10-31 15:05 UTC, Olegas commented on packages/client/src/pages/Game/Engine/Checker.ts
> +    this._ctx = ctx
Для чего этот класс задекларировал у себя свойства, которые уже есть у родителя? Например ctx - он же у нас уже объявлен и инициализируется в конструкторе родительского класса.

2023-10-31 15:05 UTC, Olegas commented on packages/client/src/pages/Game/Engine/Checker.ts
> +    const ClientRect = canvas.getBoundingClientRect()
Переменные лучше называть с маленькой буквы, иначе это путается с названиями классов и типов

2023-10-31 15:05 UTC, Olegas commented on packages/client/src/pages/Game/Engine/Checker.ts
> +      },
Добавлен обработчик, а отписки от события нет. Будет утечка.

2023-10-31 15:05 UTC, Olegas commented on packages/client/src/pages/Game/Engine/Checker.ts
> +    this._dead = true
А не надо ли тут родительский класс позвать что бы он hasDelete выставил?

2023-10-31 15:05 UTC, Olegas commented on packages/client/src/pages/Game/Engine/ChessBoard.ts
> +  private _ctx: CanvasRenderingContext2D
Еще один дуль свойства

2023-10-31 15:05 UTC, Olegas commented on packages/client/src/pages/Game/Engine/ChessBoard.ts
> +    // await spriteMap.init() инициализатор спрайтов
Не надо оставлять в проекте закомментированный код. Это приводит к замусориванию кодовой базы

2023-10-31 18:22 UTC, johnyslima commented on packages/client/src/pages/Game/Engine/ChessBoard.ts
> +    // await spriteMap.init() инициализатор спрайтов
подправил

2023-10-31 18:22 UTC, johnyslima commented on packages/client/src/pages/Game/Engine/ChessBoard.ts
> +  private _ctx: CanvasRenderingContext2D
подправил

2023-10-31 18:22 UTC, johnyslima commented on packages/client/src/pages/Game/Engine/Checker.ts
> +    this._dead = true
подправил

2023-10-31 18:23 UTC, johnyslima commented on packages/client/src/pages/Game/Engine/Checker.ts
> +      },
подправил

2023-10-31 18:23 UTC, johnyslima commented on packages/client/src/pages/Game/Engine/Checker.ts
> +    const ClientRect = canvas.getBoundingClientRect()
подправил

2023-10-31 18:23 UTC, johnyslima commented on packages/client/src/pages/Game/Engine/Checker.ts
> +    this._ctx = ctx
подправил

2023-10-31 18:25 UTC, johnyslima commented
В описании MR оставил описание. Задача была разбита на 2 части, так как была необходимость переключиться на другие задачи.

2023-11-01 18:32 UTC, Olegas commented on packages/client/src/pages/Game/Engine/GameEngine.ts
> +  private _gameLoop(nowTime: DOMHighResTimeStamp) {
@johnyslima а где эта функция вызывается? Я нашел только один reuestAnimationFrame, но он дает только один запуск. Обычно в конце анимирующей функции ставят следующий запуск.

2023-11-01 18:33 UTC, Olegas commented on packages/client/src/pages/Game/Engine/Checker.ts
> +    this.hasDelete
@johnyslima тут что-то странное написано. Зачем вообще эта функция переопределяется тут?

2023-11-01 18:34 UTC, Olegas commented on packages/client/src/pages/Game/Engine/Checkers.ts
> +    // Завершающие действия
@johnyslima зачем везде переопределена эта функция с пустым телом?

2023-11-01 18:38 UTC, Olegas approved these changes
С учетом моментов в описании задачи - работа принята. Но не все моменты ясны до конца, оставил там комментарии.

2023-11-02 08:52 UTC, merged