Redux хранилище с userSlice
cupOfTea321/chapecker pull request #18
Opened 2023-11-04 17:15 UTC by cupOfTea321

### Добавление redux хранилища 
- В проект добавлен redux-toolkit 
- Вынесен общий store с редьюсерами 
- Создана заглушка userSlice с информацией о пользователе (после регистрации) 

###[ TBD (если есть)](https://linear.app/chapecker/issue/CHA-34/dobavit-redux-hranilishe)

2023-11-05 12:24 UTC, mcf11y commented on packages/client/src/redux/services/yandexCore.ts
> +    baseUrl: 'https://ya-praktikum.tech/api/v2/',
лушче этот урл вынести куда-нибудь в константы - на случай если он может поменяться и можно было в одном месте это сделать

2023-11-05 12:24 UTC, mcf11y commented on packages/client/src/redux/services/yandexCore.ts
> +export const yandexCoreApi = createApi({
я бы это не эскпортировал наружу это - только хуки для работы

2023-11-05 12:24 UTC, mcf11y commented on packages/client/src/redux/store.ts
> +export const createStore = (
тоже не стоит экспортить

2023-11-05 12:24 UTC, mcf11y commented on packages/client/src/redux/services/yandexCore.ts
> +  reducerPath: 'yandexCoreApi',
и это в константу

2023-11-05 12:39 UTC, cupOfTea321 commented on packages/client/src/redux/services/yandexCore.ts
> +export const yandexCoreApi = createApi({
нам ведь необходимо в store обращаться к API для конфигурации, поэтому экспорт нужен

2023-11-05 12:41 UTC, cupOfTea321 commented on packages/client/src/redux/services/yandexCore.ts
> +  reducerPath: 'yandexCoreApi',
это же по сути просто имя, будто бы не стоит выносить отдельно

2023-11-05 12:43 UTC, cupOfTea321 commented on packages/client/src/redux/services/yandexCore.ts
> +    baseUrl: 'https://ya-praktikum.tech/api/v2/',
По сути baseUrl и определяется в одном месте для всех остальных эндпоинтов. Не совсем понял, зачем выносить его в константу

2023-11-05 14:22 UTC, mcf11y approved these changes

2023-11-06 12:23 UTC, IvanPeleshok commented on packages/client/src/redux/features/userSlice.ts
> +} as { data: null | User; isLoading: boolean | null; error: string | null }
Предлагаю вынести типизицию в интерфейс
```
const initialState: IState = {
```

2023-11-06 12:25 UTC, IvanPeleshok commented on packages/client/src/redux/features/userSlice.ts
> +    getUser: () => {
Полагаю так будет лучше
```
getUser: (state) => {
      return state.data
},
```

2023-11-06 12:27 UTC, IvanPeleshok commented on packages/client/src/redux/services/yandexCore.ts
> +    // prepareHeaders: (headers) => {
Если не используется, то лучше удалить (YAGNI - https://web-creator.ru/articles/yagni)

2023-11-06 12:28 UTC, IvanPeleshok requested changes
Замечательная работа!
Отлично потрудились!

Есть небольшие замечания, предлагаю доработать

Хорошего дня :)

2023-11-06 17:08 UTC, johnyslima approved these changes

2023-11-06 19:39 UTC, IvanPeleshok requested changes
Здорово, что поправили замечания, нравится 🚀 

Прошу прощения, что напутал в написании примера, отписал небольшой коммент, как должно выглядеть - поправьте пожалуйста и работа будет принята

Хорошего дня :)

2023-11-06 19:39 UTC, IvanPeleshok commented on packages/client/src/pages/Main/MainPage.tsx
> +  console.log(user)
Для какой цели отладочный код в деве?

2023-11-06 19:39 UTC, IvanPeleshok commented on packages/client/src/redux/features/userSlice.ts
> +      return state.data
Прошу прощения, вероятно я сам напутал, когда писал вам пример кода

getUser - редьюсер, редьюсер меняет состояние стора слайса (в конкретном случае)

Если вы хотите получить значение из стора, то необходимо использовать селектор с помощью хука useSelector https://redux-toolkit.js.org/tutorials/quick-start#use-redux-state-and-actions-in-react-components
Т.е для того, чтобы получить значение необходимо использовать следующий код в компоненте
```
const count = useSelector((state: RootState) => state.user.data)
```
В редьюсере же может быть следующее:
```
setUser: (state, action: PayloadAction<User>) => {
  state.user = action.payload
}
```

2023-11-07 07:08 UTC, WilhelmYakunin approved these changes
Уже использую эту ветку в  pull request Cha-32.

2023-11-07 19:20 UTC, IvanPeleshok commented on packages/client/src/redux/features/userSlice.ts
> +interface IState {
Предлагаю разделять отступами блоки, так будет аккуратнее, а как следствие, читаемее

2023-11-07 19:21 UTC, IvanPeleshok approved these changes
Всё замечательно

Есть маленький комментарий

Поздравляю, апрув!

Хорошего дня :)

2023-11-07 19:33 UTC, merged