Vityakunin/cha 32
cupOfTea321/chapecker pull request #22
Opened 2023-11-06 19:06 UTC by WilhelmYakunin

### Авторизация должна проверяться через отдельно написанный Hook или HOC (на ваш выбор, можно использовать сразу оба)

### [TBD](https://linear.app/chapecker/issue/CHA-32/avtorizaciya-dolzhna-proveryatsya-cherez-otdelno-napisannyj-hook-ili)

Singin в форме логинизации только чтобы проверить можно было редирект хотя может кому пригодиться.

2023-11-08 06:50 UTC, Vampiracus commented
Привет!

Всё очень красиво оформлено!

- Посмотрел, как это работает. Думаю, что стоит перенаправлять пользователя после авторизации или регистрации сразу на главную страницу.
- Возможно, следует также как-то говорить пользователю, как именно должны быть заполнены поля. Сообщение "Неверное имя" неинформативно

Поскольку пользователь теперь может авторизовываться, нужно научиться запрашивать в странице профиля данные о пользователе, а также добавить возможность разлогиниться. Я на всякий случай добавил в Linear эти таски на будущее

2023-11-08 13:38 UTC, johnyslima approved these changes

2023-11-08 14:26 UTC, Vampiracus commented on packages/client/src/router/router.tsx
> +  noMatch: {
Похоже, здесь опечатка: страница 500 ошибки теперь стала доступна по адресу `/505` вместо `/500`

2023-11-08 14:27 UTC, Vampiracus commented on packages/client/src/router/router.tsx
> +  noMatch: {
@WilhelmYakunin пожалуйста, исправь

2023-11-08 14:40 UTC, Vampiracus requested changes
Привет ещё раз!

Написал пару комментариев выше. Сейчас заметил серьёзный баг, поэтому отправляю ревью

На странице регистрации отправляется запрос на авторизацию. Видимо, это связано с тем, что у форм авторизации и регистрации одна и та же функция onSubmit. Нужно это исправить!

2023-11-08 19:59 UTC, WilhelmYakunin commented on packages/client/src/router/router.tsx
> +  noMatch: {
Ок, поправил

2023-11-08 20:00 UTC, WilhelmYakunin commented
> Привет ещё раз!
> 
> Написал пару комментариев выше. Сейчас заметил серьёзный баг, поэтому отправляю ревью
> 
> На странице регистрации отправляется запрос на авторизацию. Видимо, это связано с тем, что у форм авторизации и регистрации одна и та же функция onSubmit. Нужно это исправить!

Сделал рефакторинг компонентов логин и регистрации

2023-11-09 20:45 UTC, Vampiracus requested changes
Привет!

Всё супер, крутой лоадер! Есть только маленький недочет. Я указал его ниже. Пожалуйста, исправь. После этого PR можно мерджить.

2023-11-09 20:45 UTC, Vampiracus commented on packages/client/src/pages/SignUp/SignUp.tsx
> +        await signUp(fieldData)
Хуки можно вызывать только на верхнем уровне в компоненте. Здесь ты вызываешь хук внутри промиса, поэтому при попытке отправить запрос на авторизацию приложение падает
![image](https://github.com/cupOfTea321/chapecker/assets/53150722/7953a8a3-0805-4553-91c3-642964bbcd37)

Вынеси строчку
```
const navigate = useNavigate()
```
Вне промиса, тогда ошибка не будет появляться, и регистрация будет проходить

2023-11-10 06:49 UTC, Vampiracus approved these changes

2023-11-10 07:05 UTC, WilhelmYakunin commented on packages/client/src/pages/SignUp/SignUp.tsx
> +        await signUp(fieldData)
Думаю придется вернуться к авторизации позднее. Для одной такси HOC и авторизация слишком много.

2023-11-10 07:13 UTC, Vampiracus approved these changes

2023-11-10 07:21 UTC, merged