Yandex OAuth
cupOfTea321/chapecker pull request #25
Opened 2023-11-15 18:51 UTC by Vampiracus

### В приложение добавлен Яндекс OAuth

- Добавлен редьюсер с id приложения в redux-хранилище
- В профиль добавлена кнопка для выхода их аккаунта

![login page](https://github.com/cupOfTea321/chapecker/assets/53150722/aef2c607-786a-43c8-9cb5-cdd5d52732ea)
![profile page](https://github.com/cupOfTea321/chapecker/assets/53150722/527648ee-bdb8-4988-a6c2-8f7aeed952c6)

2023-11-24 08:09 UTC, nvisary commented on packages/client/src/components/ProtectedRoute/actions.ts
> +    Object.assign(config, {
можно так 
```
axios({...config,  method: 'POST',
      withCredentials: true,
      url: yandexOAuthURL,
      data: JSON.stringify({
        code,
        redirect_uri: appURL,
      }),
})
```

2023-11-24 08:10 UTC, nvisary commented on packages/client/src/pages/Login/Login.tsx
> +      .then(a => a.data)
чуть лучше будет использовать async/await 
лучше читаемость + в коде у вас чаще встречается

2023-11-24 15:50 UTC, Vampiracus commented on packages/client/src/pages/Login/Login.tsx
> +      .then(a => a.data)
Согласен что async/await синтаксис читабельнее, однако в useEffect нельзя подавать функцию, которая возвращает промис. Чтобы организовать async/await, придется весь код обернуть в промис. Кажется, от этого код не станет красивее

2023-11-24 16:02 UTC, johnyslima approved these changes

2023-11-24 16:28 UTC, Olegas commented on packages/client/src/components/ProtectedRoute/ProtectedRoute.tsx
> +    new Promise((resolve, reject) => {
Зачем делать async-функцию и не пользоваться тем, что она async? Зачем делать new Promise если можно работать с async/await здесь? Такой код сложно читать. Если переписать на async/await будет сильно проще и понятнее

2023-11-24 16:29 UTC, Olegas commented on packages/client/src/pages/Login/Login.tsx
> +      .then(a => a.data)
Не надо для этого оборачивать в промис. Можно сделать так
```
useEffect(() => {
   async function action() { ... }
   action();
}, [])
```

2023-11-24 16:31 UTC, Olegas commented on packages/client/src/pages/Login/actions.ts
> +    })
Object.assign изменяет объект, переданный в первом аргументе. После такого вызова все следующие вызовы будут с такими параметрами. Не надо так делать.

2023-11-24 16:32 UTC, Olegas requested changes
Добрый день.
Есть проблемы по коду, нужно доработать.

2023-11-25 15:23 UTC, Olegas approved these changes
Работа принята

2023-11-25 18:19 UTC, merged