Vityakunin/cha 41
cupOfTea321/chapecker pull request #29
Opened 2023-12-03 18:36 UTC by WilhelmYakunin

### Какую задачу решаем
Настроить Redux и Router в SSR

### Скриншоты

![image](https://github.com/cupOfTea321/chapecker/assets/50325829/59b26961-d087-48e2-8590-6a5824febefe)

### TBD [Настроить Redux и Router в SSR](https://linear.app/chapecker/issue/CHA-41/nastroit-redux-i-router-v-ssr)

2023-12-04 05:22 UTC, Olegas commented on packages/server/src/entry-server.tsx
> +          <SSRAppBundle />
То, что у вас строится на сервере, отличается по структуре от того, что строится на клиенте. Будут ошибки гидратации. Структура компонентов должна совпадать. Почему сделан отдельный SSRAppBundle? Почему вместо него нельзя положить App? Также отсутствует ThemeProvider который есть при клиентском построении

2023-12-04 05:24 UTC, Olegas commented on packages/server/src/entry-server.tsx
> +  serialize(data).replace(/</g, '\\\u003c')
Защита от XSS - отлично!

2023-12-04 05:26 UTC, Olegas commented on packages/server/src/store/serverSlice.ts
> +import { createSlice } from '@reduxjs/toolkit'
Почему для серверного построения создается отдельный store? По идее store должен быть один и тот же как для сервера так и для клиента. С одинаковыми редьюсерами и мидлварами.

2023-12-04 05:26 UTC, Olegas requested changes
Добрый день.
В реализации есть проблемы. Указал на них в отдельных комментариях
Нужно доработать.

2023-12-09 15:30 UTC, WilhelmYakunin commented on packages/server/src/entry-server.tsx
> +          <SSRAppBundle />
Так и было. Нужно было перестроить Protected route и добавить валидация через куки на сервере.

2023-12-09 15:31 UTC, WilhelmYakunin commented on packages/server/src/store/serverSlice.ts
> +import { createSlice } from '@reduxjs/toolkit'
Видимо я не верно понял задачу и поправил весь store.

2023-12-09 15:31 UTC, WilhelmYakunin commented on packages/server/src/entry-server.tsx
> +          <SSRAppBundle />
ThemeProvider  пока пришлось отключть из-за некорректной работы.

2023-12-09 19:10 UTC, Olegas commented on packages/client/src/App.tsx
>  import { publilRoutes, privateRoutes } from './router/router'
Опечатка в слове publicRoutes

2023-12-09 19:12 UTC, Olegas approved these changes
Работа принята

2023-12-11 16:26 UTC, merged