Kudrinma2012/cha 48 реализовать api для форума
cupOfTea321/chapecker pull request #30
Opened 2023-12-04 09:12 UTC by Vampiracus

### Создано АПИ форума

Что реализовано? — смотри [документацию](https://github.com/cupOfTea321/chapecker/blob/kudrinma2012/cha-48-%D1%80%D0%B5%D0%B0%D0%BB%D0%B8%D0%B7%D0%BE%D0%B2%D0%B0%D1%82%D1%8C-api-%D0%B4%D0%BB%D1%8F-%D1%84%D0%BE%D1%80%D1%83%D0%BC%D0%B0/packages/server/API/README.md)

### Как теперь запустить сервер?

Запустить сервер **НЕ ПОЛУЧИТСЯ**, если не запущена база данных. Чтобы её запустить:

- Убедиться, что установлен Docker ([docker для windows](https://www.docker.com/products/docker-desktop/))
- Запустить из корня проекта `docker-compose up postgres`
- При запуске сервера в корне должен лежать файл `.env` такого содержания:

```
CLIENT_PORT=3000
SERVER_PORT=3001
POSTGRES_USER=postgres
POSTGRES_PASSWORD=postgres
POSTGRES_DB=postgres
POSTGRES_PORT=5432
```

Таска по созданию более безопасных имени пользователя и пароля будет выполнена отдельно

2023-12-05 08:31 UTC, makxca commented on packages/server/API/README.md
@WilhelmYakunin Глянь документацию, пожалуйста. Стоит ли как-то изменить или дополнить ручки?

2023-12-05 08:31 UTC, makxca commented on packages/server/index.ts
@johnyslima Эльшат! Пожалуйста, попробуй у себя настроить проект, чтобы работали и мои ручки, и SSR. Думаю, можешь спокойно закоммитить изменения в этот PR, если они не слишком объемные.
Если до пятницы понять, как настроить сервер на SSR и мои ручки, не получится, обратимся к Никите

2023-12-10 06:46 UTC, Olegas commented on packages/server/API/cookies.ts
> +  return await res.json()
Совет (можно не исправлять сейчас): return await X как правило не имеет смысла, достаточно просто return X

2023-12-10 06:47 UTC, Olegas commented on packages/server/API/cookies.ts
> +      const { id } = x
Ниже в этом файле есть функция getUserId - ее можно тут использовать

2023-12-10 06:51 UTC, Olegas commented on packages/server/API/cookies.ts
> +export const setUserIDCookieOnGetUser = responseInterceptor(
Вот это решение выглядит очень неэффективным, надо что-то делать с ним. Если я все правильно понял то вы на каждый запрос к API вызываете авторизацию. Но зачем? Ведь у вас есть cookie уже, почему его просто не пробросить дальше в запросе?

2023-12-10 06:52 UTC, Olegas commented on packages/server/API/cookies.ts
> +export const setUserIDCookieOnGetUser = responseInterceptor(
Расскажите, для чего нужен этот перехватчик запросов? Что он делает?

2023-12-10 07:33 UTC, Olegas commented on packages/server/API/forum/comments/get.ts
> +      if (isNaN(topic_id) || typeof topic_id !== 'number') {
Как может быть тип не number если выше вы его только что создали как Number?

2023-12-10 07:34 UTC, Olegas commented on packages/server/API/forum/comments/get.ts
> +      let limit: number | undefined = Number(limitQ)
Как может быть тип undefined если вот он сразу же тут инициализируется?

2023-12-10 07:35 UTC, Olegas commented on packages/server/API/database/Models/Comment.ts
> +  topic_id: string | undefined
Вы ищете комментарии по ид топика. Что бы эти запросы выполнялись эффективно - нужен индекс. Внешний ключ не создает индекс

2023-12-10 07:35 UTC, cupOfTea321 commented
Отличная структура папок, всё запускается

2023-12-10 07:35 UTC, cupOfTea321 approved these changes

2023-12-10 07:37 UTC, Olegas commented on packages/server/API/database/Models/Reply.ts
> +  comment_id: string | undefined
Аналогичная проблема как с комментариями. Нужен индекс

2023-12-10 07:40 UTC, Olegas commented on packages/server/API/forum/replies/post.ts
> +    const creator_id = await getUserId(req)
Идентификатор автора вычисляете на бэке - правильное решение! 👍

2023-12-10 07:41 UTC, Olegas commented on packages/server/API/proxy/addProxyAPI.ts
> +      onProxyRes: setUserIDCookieOnGetUser,
Ага... вот для чего нужна была та функция... А зачем? http-proxy-middleware сам отлично справляется с простановкой cookie, и никакие другие функции ему не нужны.

2023-12-10 07:42 UTC, Olegas commented on yarn-error.log
Такие файлы лучше в репозиторий не складывать. Это же просто отладочный лог с ошибками.

2023-12-10 07:43 UTC, Olegas requested changes
Добрый день.
В реализации есть проблемы, нужно доработать.
Написал подробно в комментариях к коду

2023-12-10 07:48 UTC, Vampiracus commented on packages/server/API/cookies.ts
> +export const setUserIDCookieOnGetUser = responseInterceptor(
Подразумевался такой подход. Наш фронт отправляет запросы по ручке GET /auth/user каждый раз, когда приложению нужна информация о пользователе. Чтобы на сервере не отправлять дублирующие запросы, просто перехватывается ответ, и id пользователя запоминается в куке.
Видимо, что-то пошло не так, и, чтобы получать id пользователя, я начал отправлять запрос самостоятельно по этой ручке, хотя id у меня уже есть. Сейчас исправлю

2023-12-10 08:48 UTC, Vampiracus commented on packages/server/API/cookies.ts
> +      const { id } = x
Не совсем. Та функция работает с req типа `Express.Request`, а здесь у нас req типа `IncomingMessage`

2023-12-10 09:08 UTC, Vampiracus commented on packages/server/API/proxy/addProxyAPI.ts
> +      onProxyRes: setUserIDCookieOnGetUser,
На всякий случай ещё раз здесь поясню

http-proxy-middleware проставляет куки от API Практикума, но чтобы не ходить каждый раз туда за id пользователя по этим кукам, сервер ходит туда только когда с фронта приходит запрос `GET api/v2/auth/user` и выставляет куку `userid`, чтобы в дальнейшем смотреть id пользователя именно в куке

2023-12-10 09:13 UTC, Vampiracus commented on yarn-error.log
Действительно. Добавил логи в гитигнор

2023-12-10 16:57 UTC, WilhelmYakunin commented on packages/server/API/README.md
Смотрю

2023-12-10 19:35 UTC, WilhelmYakunin commented on packages/server/API/forum/topics/post.ts
> +    const { title } = req.body
Срабатывает. Но можем еще добавить Description. Соответственно добавить такое поле в ответ сервера на запрос о всех форумах.
Можно улучшить. Если захочешь, то потренироваться с загрузкой картинок.
Еще, сделал коммит с кодом на клиенте. Обрати внимание, что "/v2" пришлось убрать, т.к. по ручке с этим префиксом сервер не отвечает.

2023-12-10 19:39 UTC, WilhelmYakunin reviewed
Добавил коммит и комментарий.
Postman не показал ответ сервера, так что Topics и Replies проверю в процессе настройки на клиенте ;)
Очень лаконичное обращение к базе, понятно все, класс!

2023-12-11 16:01 UTC, Olegas approved these changes
Работа принята. Но честно говоря я так и не смог понять, зачем перехватчик для мидлвары если она может работать сама.
То есть вы просто отправляете запросы на Яндекс и возвращаете ответы. При авторизации в ответе будет кука, она вместе с ответом прилетит клиенту, он ее поставит и будет дальше вам передавать, вы так же ее будете использовать.

2023-12-11 17:13 UTC, merged