cha 47 серверная инфраструктура
cupOfTea321/chapecker pull request #37
Opened 2023-12-13 16:12 UTC by johnyslima

### Какую задачу решаем
[CHA-47](https://linear.app/chapecker/issue/CHA-47/servernaya-infrastruktura-dlya-foruma-emodzi-i-temizacii)

### Скриншоты/видяшка (если есть)

### TBD (если есть)

2023-12-13 16:47 UTC, Vampiracus requested changes
Привет!

Извини за прямоту, но, хотя изменений немного, совершенно непонятно, как проверять их. Я попробовал сделать всё в соответствии с текущей инструкцией в REAMDE.md проекта, но у меня не поднялся докер-контейнер. А в консоли вылетела ошибка поднятия сервера, скорее всего обусловленная тем, что не поднята БД

Пожалуйста, измени readme.md так, чтобы там было описано, как запустить докер с нашим проектом, скачав репозиторий локально на комп

2023-12-13 16:47 UTC, Vampiracus commented on packages/client/vite.config.ts
>    },
Почему поменялись адреса клиента и сервера? Почему именно такие адреса?

2023-12-13 19:26 UTC, johnyslima commented on packages/client/vite.config.ts
>    },
порты он берет с env файла. Это рудимент. Исправли

2023-12-13 19:27 UTC, johnyslima commented on packages/client/vite.config.ts
>    },
Попробуй еще раз запустить сборку, я влил изменения. 
Я пользуюсь командой docker compose up -d

2023-12-13 20:20 UTC, IvanPeleshok requested changes
Проделана большая работа!
Отлично потрудились!

Оставил комментарии по улучшению реализации фичи

Обязательно покажите работу своей команде, нужен минимум один апрув от вашей команды

Хорошего дня :)

2023-12-13 20:20 UTC, IvanPeleshok commented on docker-compose.yml
Предлагаю указать явно networks для сервисов:
"Understanding Docker Compose Files for Networking"
https://ioflood.com/blog/docker-compose-network-simplify-your-docker-network-management/#:~:text=Final%20Thoughts-,Understanding%20Docker%20Compose%20Files%20for%20Networking,-Connecting%20services%20across

2023-12-13 20:50 UTC, Vampiracus commented
Подскажи, пожалуйста, в чем может быть проблема?
![image](https://github.com/cupOfTea321/chapecker/assets/53150722/ca586d98-8471-4bad-941d-ac3b255bbf51)

2023-12-13 21:09 UTC, johnyslima commented
> Подскажи, пожалуйста, в чем может быть проблема? ![image](https://private-user-images.githubusercontent.com/53150722/290325246-ca586d98-8471-4bad-941d-ac3b255bbf51.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI1MDE5MDQsIm5iZiI6MTcwMjUwMTYwNCwicGF0aCI6Ii81MzE1MDcyMi8yOTAzMjUyNDYtY2E1ODZkOTgtODQ3MS00YmFkLTk0MWQtYWMzYjI1NWJiZjUxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEzVDIxMDY0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg5NGUxODU1MzU1NTYyMjlkM2ZlMTgxNGFhYTY4YmRjN2FlNDkxMzNlZTUyNDBlM2VkNDlhNzg1YzNiY2M3YmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gwPjjObo8cXSr1ADdo7orWcPwaXz-0soCmOb13uHOaI)



> Подскажи, пожалуйста, в чем может быть проблема? ![image](https://private-user-images.githubusercontent.com/53150722/290325246-ca586d98-8471-4bad-941d-ac3b255bbf51.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI1MDE5MDQsIm5iZiI6MTcwMjUwMTYwNCwicGF0aCI6Ii81MzE1MDcyMi8yOTAzMjUyNDYtY2E1ODZkOTgtODQ3MS00YmFkLTk0MWQtYWMzYjI1NWJiZjUxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEzVDIxMDY0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg5NGUxODU1MzU1NTYyMjlkM2ZlMTgxNGFhYTY4YmRjN2FlNDkxMzNlZTUyNDBlM2VkNDlhNzg1YzNiY2M3YmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gwPjjObo8cXSr1ADdo7orWcPwaXz-0soCmOb13uHOaI)

попробуй удалить node_modules, package-lock, yarn.lock везде и запустить заново

2023-12-13 21:34 UTC, Vampiracus approved these changes
Доброй ночи
В общем, у меня начало не хватать места на диске, и придется переустановить докер... В остальном все ок)

2023-12-14 11:42 UTC, johnyslima commented on docker-compose.yml
хорошо, попробую в ближайшее время

2023-12-14 11:45 UTC, johnyslima commented on docker-compose.yml
докрутил

2023-12-14 12:11 UTC, johnyslima commented on docker-compose.yml
также получен апрув от члена команды @IvanPeleshok

2023-12-14 21:11 UTC, IvanPeleshok approved these changes
Всё здорово, апрув!
Хорошего дня :)

2023-12-15 01:56 UTC, merged