Vityakunin/cha 53 поддержать api форума на клиенте
cupOfTea321/chapecker pull request #38
Opened 2023-12-17 18:35 UTC by WilhelmYakunin

### Какую задачу решаем (поддержать API форума на клиенте)[https://linear.app/chapecker/issue/CHA-53/podderzhat-api-foruma-na-kliente]

### Скриншоты/видяшка 
![image](https://github.com/cupOfTea321/chapecker/assets/50325829/e1b074ea-11d5-4010-81b3-d0791965d8d8)

2023-12-18 08:45 UTC, Vampiracus requested changes
Привет!

Проделана очень большая работа!

Есть несколько вопросов. Я постарался все вопросы написать с привязкой к коду. 

Пожалуйста, не мерджи этот PR в мейн, пока не убедимся, что все работает.

2023-12-18 08:45 UTC, makxca commented on packages/client/src/pages/Forum/ForumPage.tsx
Хорошо бы вынести табы в отдельный компонент

2023-12-18 08:45 UTC, Vampiracus commented on packages/client/src/pages/Forum/components/controls/paginationControl.tsx
Где используется то, что написано в этом файле? Я поискал по ПР, и не нашел, где импортируется этот файл. Возможно, его лучше удалить?

2023-12-18 08:45 UTC, Vampiracus commented on packages/client/src/pages/Forum/ForumPage.tsx
>            </section>
Я создал 20 топиков, нажал на "На странице: 20", но на странице не стало отображаться 20 топиков :(
Может, я что-то сделал не так? Как оно должно работать?
![image](https://github.com/cupOfTea321/chapecker/assets/53150722/4dd401c4-08fa-4374-9197-e0cb0aadb06e)

2023-12-18 08:45 UTC, Vampiracus commented on packages/client/src/pages/Forum/actions.ts
> +  limit: number
Покликал на пагинацию. Заметил, что у тебя offset равен номеру страницы.

![image](https://github.com/cupOfTea321/chapecker/assets/53150722/d01e516c-1350-4c07-9de8-846bd66a2662)

На сервер надо отправлять именно offset, то есть количество записей, которые надо пропустить: offset=(page-1)*limit. Например, если на странице показывается 10 элементов, и мы хотим посмотреть третью страницу, то надо сделать offset=20, чтобы пропустить 20 элементов первых двух страниц.
Обрати внимание, что на первой странице offset должен быть равен 0.

2023-12-18 08:45 UTC, Vampiracus commented on packages/client/src/pages/Forum/components/forumPreviewTable/forumPreviewTable.tsx
> +                  {title}
Зачем отправляет на фиксированный хост?
Я запускаю проект на клиенте, и, по-хорошему, меня не должно перекидывать на сервер
Вообще, если я правильно понял суть SSR, он должен быть только для стартовой страницы, причем он ничего не умеет?
Я думаю, следует сделать отрисовку форумов на том же хосте, к которому мы обращаемся, чтобы получить таблицу форумов

2023-12-18 08:45 UTC, Vampiracus commented on packages/client/src/pages/ForumItemPage/ForumItemPage.tsx
Почему-то эта страница у меня вообще не отображается
Что надо сделать, чтобы отображалась?
![image](https://github.com/cupOfTea321/chapecker/assets/53150722/fcb02625-a7ce-4e43-84f8-a3d241d4fe03)

2023-12-19 18:14 UTC, WilhelmYakunin commented on packages/client/src/pages/ForumItemPage/ForumItemPage.tsx
Поправил

2023-12-19 18:17 UTC, WilhelmYakunin commented on packages/client/src/pages/Forum/components/controls/paginationControl.tsx
Это был файл из пробной версии развития кода

2023-12-19 18:55 UTC, WilhelmYakunin commented on packages/client/src/pages/Forum/components/forumPreviewTable/forumPreviewTable.tsx
> +                  {title}
С SSR все не так просто. По сути с SSR нужно по новому выстраивать приложение. Либо, как сейчас, работа не стабильна.
Но локация теперь динамически подставляться будет

2023-12-19 20:32 UTC, WilhelmYakunin commented on packages/client/src/pages/Forum/actions.ts
> +  limit: number
Поправил, но полностью будет работать после сливания с обновленным кодом бэка

2023-12-19 20:32 UTC, WilhelmYakunin commented on packages/client/src/pages/Forum/ForumPage.tsx
>            </section>
Поправил

2023-12-19 20:32 UTC, WilhelmYakunin commented on packages/client/src/pages/Forum/ForumPage.tsx
Думаю на mui переделать

2023-12-20 10:11 UTC, Vampiracus commented on packages/client/src/pages/Forum/actions.ts
> +  limit: number
Сейчас пагинация работает с ошибкой

Я создал 12 топиков
![image](https://github.com/cupOfTea321/chapecker/assets/53150722/1b93aab7-4f88-4cdc-b8d1-91084b5ee11b)

Выбрал отображение 10 топиков на странице, но мне не предлагается перейти на 2 страницу:
![image](https://github.com/cupOfTea321/chapecker/assets/53150722/6c68ceab-d5f5-43dc-a927-615e57b5b177)

2023-12-20 10:13 UTC, Vampiracus commented on packages/client/src/pages/Forum/actions.ts
> +  limit: number
Думаю, что если нужна функциональность из соседнего PR, то её можно подлить в эту ветку и работать с ней. 
Главное тогда будет текущий ПР влить в мейн после соседнего

2023-12-20 10:36 UTC, Vampiracus requested changes
Привет!

Вижу, что баги были поправлены: работает страница топика, можно писать комментарии и реплаи. Прикольно, что при загрузке страницы топика под сообщением рисуется лоадер, сигнализируя, что идет подгрузка реплаев

Осталось все же несколько вопросов и проблем:

- Поле topic.description (начальное сообщение) нигде не отображается. Стоит ли это поле убрать из БД или планируется его использовать в дальнейшем?

- Возможно, следует добавить кнопку возврата из окна одного топика в окно со всеми топиками. Сейчас когда я хочу посмотреть другой топик я жму кнопку "Назад" браузера (работаю в Хроме), возвращаюсь на окно топиков, жму по другому топику, но сообщения нового топика не подгружаются: отображаются сообщения первого выбранного топика. Я думаю, это особенность Хрома. Не думаю, что баг критичный, потому что если обновить страницу, то подгружаются правильные сообщения.
- Аналогично некритично, но думаю, что следует заново подгружать все ответы на комментарий, на который отвечает пользователь. Сейчас когда я отправляю реплай, у меня очищается поле ввода и отправляется запрос, но без обновления страницы мой реплай не отображается.
- Под одним из файлов я написал, что не работает пагинация (переключение страниц). Думаю, следует её настроить здесь же. Замечу, что эта же проблема актуальна на странице отдельного топика по отношению к комментариям: если комментариев больше 10, а на странице отображается максимум 10, то последние никак не увидеть
![image](https://github.com/cupOfTea321/chapecker/assets/53150722/66f0d87e-d8bd-434a-846a-4fd26ac2daa9)
- Проблема с реплаями: если их больше 10, то последние реплаи нельзя увидеть. Автоматически выставляется limit в 10 реплаев. Стоит либо запрашивать все реплаи (запросить их число, затем установить limit равный этому числу), либо, что гораздо проще, просто установить limit порядка 10**3, чтобы подгружались все реплаи

Несмотря на перечисленное, думаю, ПР можно мерджить уже если будет решена проблема с пагинацией на странице топиков и на странице отдельного топика.

2023-12-20 19:54 UTC, IvanPeleshok requested changes
Проделана большая работа!
Отлично потрудились!

Есть замечания, предлагаю доработать те комментарии, которые вам показались наиболее критическими
Будет здорово, если найдёте время на то, чтобы поправить все замечания
Комментарии писал один раз для одного вида замечаний, предлагаю однотипные моменты поправить везде

Отлично, что не забываете использовать try / catch, чтобы обработать исключения

Хорошего дня :)

2023-12-20 19:54 UTC, IvanPeleshok commented on packages/client/src/pages/Forum/ForumPage.tsx
> +  const limits = [10, 20, 30]
Можно вынести в константу вне компонента, т.к данная переменная будет пересоздаваться при каждом ререндере

2023-12-20 19:54 UTC, IvanPeleshok commented on packages/client/src/pages/Forum/ForumPage.tsx
> +  const pages =
Вижу, что используете useCallback
В данном случае, отлично бы подошёл хук useMemo
https://react.dev/reference/react/useMemo

2023-12-20 19:54 UTC, IvanPeleshok commented on packages/client/src/pages/Forum/actions.ts
> +    ...config,
Для цели унификации логики и создания экземпляра axios с настроенной конфигураций отлично подошёл бы https://axios-http.com/ru/docs/instance

2023-12-20 19:54 UTC, IvanPeleshok commented on packages/client/src/pages/Forum/components/forumPreviewTable/forumPreviewTable.tsx
> +  forums: 'idle' | ITopic[]
Много где используется строковая idle

Предлагаю её вынести в константу и переиспользовать

2023-12-20 19:54 UTC, IvanPeleshok commented on packages/client/src/pages/Forum/components/forumPreviewTable/forumPreviewTable.tsx
> +  if (forums === 'idle' || forums.length === 0) return <></>
Рекомендация:
Писать if используя `{ }` - такое читать проще

Т.к это важный смысловой блок, предлагаю отделять его хотя бы пробелами от объявления констант и т.д

2023-12-20 19:54 UTC, IvanPeleshok commented on packages/client/src/pages/Forum/components/forumPreviewTable/forumPreviewTable.tsx
> +        created.getHours() +
Предлагаю вынести в константу с контекстным названием
```
const переменная = created.getHours()
   + ':'
   + created.getMinutes() < 10 ? '0' + created.getMinutes() : created.getMinutes()
 )

return переменная
```

Рекомендация: стоит выносить магические значения в переменную (`10`)
Какой контекст она имеет?

2023-12-20 19:54 UTC, IvanPeleshok commented on packages/client/src/pages/Forum/components/newTopicForm/actions.ts
> +  [x: string]: unknown
Есть ли возможность описать интерфейс параметров?

2023-12-20 19:54 UTC, IvanPeleshok commented on packages/client/src/pages/ForumItemPage/ForumItemPage.tsx
> +  if (!id) return <Navigate to={privateRoutes.forum.path} />
Очень сложно будет обратить внимание на возврат JSX среди объявления переменных и функций

Предлагаю использовать if {} и отступы

2023-12-20 19:54 UTC, IvanPeleshok commented on packages/client/src/pages/ForumItemPage/components/addMessageFrame/addMessageFrame.tsx
> +  const { first_name, second_name } = useTypedSelector(getUserData) as IUser
Для чего кастить тип, если у вас используется useTypedSelector?
Он не выводит тип селектора?

2023-12-20 19:54 UTC, IvanPeleshok commented on packages/client/src/pages/ForumItemPage/components/addMessageFrame/styles.scss
> +        display: flex;
Везде отступы по 2 проблема, тут 4

2023-12-20 19:54 UTC, IvanPeleshok commented on packages/client/src/pages/ForumItemPage/components/author/author.tsx
> +  return load ? <Loader /> : rendeContent()
Так запись выглядит понятнее, имхо
```
if (load) {
  return <Loader>
)

return  user
 ? <span>{user.first_name + ' ' + user.second_name}</span>
 :  <>Не удалось загрузить имя</>
)
```

2023-12-20 19:54 UTC, IvanPeleshok commented on packages/client/src/pages/ForumItemPage/components/forumMessagesList/styles.scss
> +    &__replyContainer {
Отступы везде 2, тут 4

2023-12-20 19:54 UTC, IvanPeleshok commented on packages/client/src/pages/ForumItemPage/components/forumMessagesList/forumMessagesList.tsx
> +                <span>{getTime(new Date(createdAt))}</span>
Будет пересоздаваться при каждом ререндера компонента

Можно подумать об оптимизации флоу данных (возможно имеет смысл прокидывать уже готовы для отрисовки данные)

2023-12-25 14:46 UTC, WilhelmYakunin commented on packages/client/src/pages/Forum/ForumPage.tsx
> +  const limits = [10, 20, 30]
Согласен

2023-12-25 17:58 UTC, WilhelmYakunin commented on packages/client/src/pages/ForumItemPage/components/author/author.tsx
> +  return load ? <Loader /> : rendeContent()
Сделал апдейт на бэке. Теперь имя приходит с сервера.

2023-12-25 17:59 UTC, WilhelmYakunin commented on packages/client/src/pages/ForumItemPage/components/forumMessagesList/forumMessagesList.tsx
> +                <span>{getTime(new Date(createdAt))}</span>
Сделал апдейт на бэке. Теперь данные автора приходят от сервера.

2023-12-25 19:00 UTC, WilhelmYakunin commented on packages/client/src/pages/ForumItemPage/components/addMessageFrame/styles.scss
> +        display: flex;
Вроде везде 4...

2023-12-25 19:05 UTC, WilhelmYakunin commented on packages/client/src/pages/ForumItemPage/ForumItemPage.tsx
> +  if (!id) return <Navigate to={privateRoutes.forum.path} />
Ок

2023-12-25 19:05 UTC, WilhelmYakunin commented on packages/client/src/pages/ForumItemPage/components/forumMessagesList/styles.scss
> +    &__replyContainer {
Вроде везде 4...

2023-12-25 19:07 UTC, WilhelmYakunin commented on packages/client/src/pages/Forum/components/forumPreviewTable/forumPreviewTable.tsx
> +  if (forums === 'idle' || forums.length === 0) return <></>
Ok

2023-12-25 19:30 UTC, WilhelmYakunin commented on packages/client/src/pages/Forum/ForumPage.tsx
> +  const pages =
Не уверен, что я понимаю правильно.
Обернуть const topics = useTypedSelector(getForumData) 
--> 
const topics = useMemo(() => useTypedSelector(getForumData), [useTypedSelector(getForumData)])?
Но в проекте Redux Toolkit и селкторы из коробки используют Reselect и значит мемоизацию [redux tlk](https://redux-toolkit.js.org/api/createSelector)

2023-12-25 19:31 UTC, WilhelmYakunin commented on packages/client/src/pages/Forum/ForumPage.tsx
> +  const limits = [10, 20, 30]
Ok

2023-12-25 19:34 UTC, WilhelmYakunin commented on packages/client/src/pages/Forum/components/forumPreviewTable/forumPreviewTable.tsx
> +  forums: 'idle' | ITopic[]
Вынес. Спасибо за комментарий

2023-12-25 19:40 UTC, WilhelmYakunin commented on packages/client/src/pages/Forum/actions.ts
> +    ...config,
У Форума и Странице топика несколько компонентов и у каждого может быть свой конфиг. Поэтому пока без axios instance.

2023-12-25 23:53 UTC, WilhelmYakunin commented
> Привет!
> 
> Вижу, что баги были поправлены: работает страница топика, можно писать комментарии и реплаи. Прикольно, что при загрузке страницы топика под сообщением рисуется лоадер, сигнализируя, что идет подгрузка реплаев
> 
> Осталось все же несколько вопросов и проблем:
> 
> * Поле topic.description (начальное сообщение) нигде не отображается. Стоит ли это поле убрать из БД или планируется его использовать в дальнейшем?
> * Возможно, следует добавить кнопку возврата из окна одного топика в окно со всеми топиками. Сейчас когда я хочу посмотреть другой топик я жму кнопку "Назад" браузера (работаю в Хроме), возвращаюсь на окно топиков, жму по другому топику, но сообщения нового топика не подгружаются: отображаются сообщения первого выбранного топика. Я думаю, это особенность Хрома. Не думаю, что баг критичный, потому что если обновить страницу, то подгружаются правильные сообщения.
> * Аналогично некритично, но думаю, что следует заново подгружать все ответы на комментарий, на который отвечает пользователь. Сейчас когда я отправляю реплай, у меня очищается поле ввода и отправляется запрос, но без обновления страницы мой реплай не отображается.
> * Под одним из файлов я написал, что не работает пагинация (переключение страниц). Думаю, следует её настроить здесь же. Замечу, что эта же проблема актуальна на странице отдельного топика по отношению к комментариям: если комментариев больше 10, а на странице отображается максимум 10, то последние никак не увидеть
>   ![image](https://private-user-images.githubusercontent.com/53150722/291863408-66f0d87e-d8bd-434a-846a-4fd26ac2daa9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM1NDg2MzEsIm5iZiI6MTcwMzU0ODMzMSwicGF0aCI6Ii81MzE1MDcyMi8yOTE4NjM0MDgtNjZmMGQ4N2UtZDhiZC00MzRhLTg0NmEtNGZkMjZhYzJkYWE5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI1VDIzNTIxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdjYzE3OTE2YTU1ZjBiMmY0YjQ3ZDA5ODkwNTlkYjJiNGI2MDUxMmRlYThhN2RhZWFlYTRkNjRlOGM2MmU4MGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pMLdVdp33cY-MK1tPNCzw9YpbUFoQ96E4w44WyFgpA8)
> * Проблема с реплаями: если их больше 10, то последние реплаи нельзя увидеть. Автоматически выставляется limit в 10 реплаев. Стоит либо запрашивать все реплаи, запросив сначала их число, и затем установив limit равный этому числу; либо, что гораздо проще, просто установить limit порядка 10**3, чтобы подгружались все реплаи
> 
> Несмотря на перечисленное, думаю, ПР можно мерджить уже если будет решена проблема с пагинацией на странице топиков и на странице отдельного топика.

Привет!
Спасибо за ревю.
Вроде все учел в новой версии. 
Слил свой коммит с соседеней веткой. На бэке немного правил методы. Хулиганил в общем ;)

2023-12-25 23:54 UTC, WilhelmYakunin commented
> Проделана большая работа! Отлично потрудились!
> 
> Есть замечания, предлагаю доработать те комментарии, которые вам показались наиболее критическими Будет здорово, если найдёте время на то, чтобы поправить все замечания Комментарии писал один раз для одного вида замечаний, предлагаю однотипные моменты поправить везде в рамках PR
> 
> Отлично, что не забываете использовать try / catch, чтобы обработать исключения
> 
> Хорошего дня :)

Спасибо за ревю.
Многое поменял.
Форум стал еще краше ;)

2023-12-26 18:28 UTC, IvanPeleshok approved these changes
Отлично потрудились!

Работа не имеет критических замечаний
Поздравляю, апрув 🚀

2023-12-27 18:38 UTC, Vampiracus requested changes
Привет!

Ура, почти все готово!)

Пагинация работает отлично!

Круто, что сделал подгрузку реплаев по клику!
![image](https://github.com/cupOfTea321/chapecker/assets/53150722/42b355d0-f60a-4430-a242-32ad81f1a03c)

Все же, стоит исправить два критичных момента перед мерджом. Я оставил соответствующие комментарии в коде

Ещё, здесь некритично, но думаю, что после создания топика стоит пользователя все же перемещать на окно с топиками (по адресу `/forum`, либо уведомлять, что топик создан. А то жмешь на кнопку, и непонятно, произошло ли что-то

2023-12-27 18:38 UTC, Vampiracus commented on .env.sample
Не надо удалять этот файл. В нем хранится информация для запуска PostgreSQL. Если тебе нужен файл `.env`, пожалуйста, сделай копию этого файла и назови её соответствующим образом.

Или просто выполни скрипт init.js. Для этого из корня директории:
```bash
node init.js
```

2023-12-27 18:38 UTC, Vampiracus commented on packages/client/index.html
>    <meta charset="UTF-8" />
Тут действительно есть проблема:

Открыл страницу конкретного топика. При попытке обновить страницу не подгружается скрипт main.tsx, из-за чего приложение не запускается. Он почему-то думает, что её надо запрашивать из адреса `forum/src/main.tsx`, а не просто `src/main.tsx`.

Я поменял здесь на
```HTML
<base href="/">
```
И у меня заработало. Не знаю, насколько это верное решение, но точно что-то нужно сделать, а то приложение не подгружает скрипты.

2023-12-29 14:45 UTC, WilhelmYakunin commented on packages/client/src/pages/Forum/ForumPage.tsx
Перенес код на mui tabs.

2023-12-29 14:46 UTC, WilhelmYakunin commented on packages/client/src/pages/Forum/actions.ts
> +  limit: number
Теперь все должно быть - ОК

2023-12-29 14:47 UTC, WilhelmYakunin commented on .env.sample
Я не удалял. Но чтобы запустить приложение переименовал env.example в env

2023-12-29 21:33 UTC, Vampiracus reviewed
Привет!

Чекну ПР, позже. Сейчас заметил: пожалуйста, переименуй .env.example в .env.sample (это исходное название файла, и именно оно фигурирует в скрипте `init.js`)

2023-12-31 06:41 UTC, Vampiracus approved these changes
Привет!

Ура, все работает! Можно коммитить

2023-12-31 06:41 UTC, Vampiracus commented on .env.example
Зачем файл переименован? Надо переименовать обратно в `.env.sample`

2023-12-31 06:42 UTC, Vampiracus commented on .env.example
Я переименовал файл обратно прямо из гитхаба. Решил, что это ок, потому что можно сделать в 2 клика.

2023-12-31 18:58 UTC, merged