Forum front end
cupOfTea321/chapecker pull request #7
Opened 2023-10-22 16:28 UTC by WilhelmYakunin

### Вёрстка страницы форума
Сделать роут для страницы форума 

Сверстать экраны форума: 

- экран создания топика, 

- экран со всем топиками, 

- экран одного топика с комментами, 

- функциональность добавления комментария к топику.

Форум — страница, на которой пользователи могут создавать темы, оставлять в этих темах комментарии и отвечать на них. API вам предстоит написать самостоятельно в восьмом спринте.

### Скриншоты/видяшка 
![image](https://github.com/cupOfTea321/chapecker/assets/50325829/ade23050-ccc7-4b22-8dac-7d5437c51fb9)

![image](https://github.com/cupOfTea321/chapecker/assets/50325829/79776b4b-8121-41c8-955c-3e50f6ee5c5d)

![image](https://github.com/cupOfTea321/chapecker/assets/50325829/b934c6f2-43ab-41b3-b7e5-b0ef40c50e34)

2023-10-23 14:50 UTC, Vampiracus requested changes
Проделана большая работа!

У меня есть несколько комментариев:

- Крутой бэкгаунд!
- Понятно организованы файлы
- Заметил, что текст везде на английском языке. Для единства оформления надо будет определиться, писать страницы с ориентиром на английский язык или все же на русский. Я создам соответствующий тред в чате

Ещё есть два момента, которые нужно поправить:
- Перенести компоненты форума из `src/components`
- Сделать, чтобы приложение не падало при попытке найти несуществующий форум
Я расписал эти два вопроса подробнее в комментариях к коду

2023-10-23 14:50 UTC, makxca commented on packages/client/src/pages/ForumItemPage/ForumItemPage.tsx
> +  const { theme, messages }: TForum = forum
Если правильно понял, кидает ошибку, если нет форума с таким id. Возможно, лучше перенаправлять на страницу 404 Not Found, чтобы приложение не падало?

2023-10-23 14:50 UTC, makxca commented on packages/client/src/pages/Forum/ForumPage.tsx
> +        </ul>
Круто, что не стал дублировать код для двух табов, а вынес их как рендер по массиву: если захотим, сможем дописать ещё табов.
Возможно, табы можно вынести отдельным компонентом, чтобы упростить вид элемента Forum?

2023-10-23 14:50 UTC, Vampiracus commented on packages/client/src/pages/ForumItemPage/ForumItemPage.tsx
> +
Не все элементы среди forumMessagesFrame, forumMessagesList, forumPreviewTable и newTopicForm стоит хранить в `src/components`. Часть или вообще все можно перенести в `src/pages/Forum/components` или в `src/components/Forum`.
Дело в том, что если все кастомные компоненты складывать в `src/components`, папка станет захламлена и лишена организации. Кроме того, эти компоненты сложно переиспользовать в разных частях приложения и, скорее всего, они будут использоваться только в странице форума. Тогда логично хранить их рядом с форумом.

2023-10-23 18:53 UTC, WilhelmYakunin commented on packages/client/src/pages/ForumItemPage/ForumItemPage.tsx
> +
Согласен

2023-10-23 19:13 UTC, WilhelmYakunin commented on packages/client/src/pages/ForumItemPage/ForumItemPage.tsx
> +  const { theme, messages }: TForum = forum
Согласен.  
Но есть момент: Возвращать должен ReactNode - поэтому возвращает <div></div>
И еще. Изначально планировал, что здесь будет запрос на сервер и сервер возвращает ошибку - нет такого форума. Т.е. как можно больше логики на сервере. Т.е. уже другая тема будет.

2023-10-23 19:37 UTC, WilhelmYakunin commented
> Проделана большая работа!
> 
> У меня есть несколько комментариев:
> 
> * Крутой бэкгаунд!
> * Понятно организованы файлы
> * Заметил, что текст везде на английском языке. Для единства оформления надо будет определиться, писать страницы с ориентиром на английский язык или все же на русский. Я создам соответствующий тред в чате
> 
> Ещё есть два момента, которые нужно поправить:
> 
> * Перенести компоненты форума из `src/components`
> * Сделать, чтобы приложение не падало при попытке найти несуществующий форум
> 
> Я расписал эти два вопроса подробнее в комментариях к коду

Отличный фидбэк. Я не думал, что правлю ошибки, но понимал, что мой уровень растет и проект действительно улучшается. Сделал несколько добавок: добавление мессенджа добавляет число сообщений на страницы со всеми форумами, svg иконки для экранов до 450px  без lable.

2023-10-24 06:25 UTC, Vampiracus approved these changes
Класс!

2023-10-25 15:43 UTC, IvanPeleshok commented on packages/client/src/App.scss
> +html,
Предлагаю вынести обнуление стилий в отдельный модуль scss / css

2023-10-25 15:45 UTC, IvanPeleshok commented on packages/client/src/pages/Forum/ForumPage.tsx
> +        {tabsArr.map((tab, i) => (
После того, когда мок данные исчезнут - поправите split / join?
Выглядит по меньшей мере странно

2023-10-25 15:45 UTC, IvanPeleshok commented on packages/client/src/pages/Forum/ForumPage.tsx
> +            defaultChecked={i === 0}
!index

2023-10-25 15:46 UTC, IvanPeleshok commented on packages/client/src/pages/Forum/ForumPage.tsx
> +                    src={getImageUrl('../assets/' + tabHtmlAllias + '.svg')}
Лучше вынести в перменную

2023-10-25 16:01 UTC, IvanPeleshok commented on packages/client/src/pages/Forum/components/newTopicForm/newTopicForm.tsx
> +    handleLabelInput: useCallback((e: ChangeEvent) => {
Объект сам по себе будет пересоздаваться на каждый ререндер

Полагаю, что обёртка в виде объекта будет избыточной, можно убрать

2023-10-25 16:02 UTC, IvanPeleshok commented on packages/client/src/pages/ForumItemPage/ForumItemPage.tsx
> +  if (!forum) return <Navigate to="*" />
Предлагаю выделить данный момент в коде, т.к сейчас jsx сливается с остальным функционалом
```
if (!forum) {
  return JSX
}

...
```

2023-10-25 16:03 UTC, IvanPeleshok commented on packages/client/src/pages/ForumItemPage/ForumItemPage.tsx
> +  const callbacks = {
Аналогично

2023-10-25 16:08 UTC, IvanPeleshok approved these changes
Добрый день!

Проделана огромная работа!
Здорово постарались

Есть незначительные замечания, предлагаю доработать во время интеграции апи со стороны сервера

Поскольку работа не имеет значительных замечаний, поздравляю, апрув

Хорошего дня :)

2023-10-25 16:54 UTC, merged